AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
    - "pkg/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 12

Metrics/ParameterLists:
  Max: 8
  CountKeywordArgs: false

Metrics/ClassLength:
  Max: 150

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Gemspec/DevelopmentDependencies:
  Enabled: false

Style/MultipleComparison:
  Exclude:
    - "spec/**/*"

Style/HashExcept:
  Exclude:
    - "spec/**/*"
