steps:
  - group: ":ruby: Build & Test"
    steps:
      - label: ":ruby: Ruby 3.2"
        command: .buildkite/steps/build-and-test.sh
        image: "ruby:3.2"

      - label: ":ruby: Ruby 3.3"
        command: .buildkite/steps/build-and-test.sh
        image: "ruby:3.3"

      - label: ":ruby: Ruby 3.4"
        command: .buildkite/steps/build-and-test.sh
        image: "ruby:3.4"

  - label: ":rubocop: Lint"
    command:
      - bundle install
      - bundle exec rubocop
    image: "ruby:3.4"

  - label: ":rust: Cargo Check & Clippy"
    command: .buildkite/steps/clippy.sh
    image: "ruby:3.4"
